import { z } from 'zod';

export const bookSchema = z.object({
  title: z.string(),
  original_title: z.string().optional(),
  description: z.string().optional(),
  category: z.enum([
    'economics',
    'law',
    'mathematics',
    'political-science',
    'sociology',
    'philosophy',
    'physics',
    'chemistry',
    'biology',
    'computer-science',
    'psychology',
    'history',
    'literature',
    'engineering',
    'biomedical-engineering',
    'medicine',
    'business',
    'art',
    'music',
    'education',
    'environmental-science',
    'anthropology',
    'geography',
    'linguistics',
  ]),
  level: z.enum(['undergraduate', 'graduate', 'advanced']),
  isbn: z.string().optional(),
  author: z.string(),
  publisher: z.string().optional(),
  year: z.number().optional(),
  amazonLink: z.string().url().optional(),
  tags: z.array(z.string()).default([]),
  featured: z.boolean().default(false),
  difficulty: z.enum(['beginner', 'intermediate', 'advanced']).default('intermediate'),
  cover: z.string().optional(),
  price: z.string().optional(),
  rating: z.number().min(1).max(5).optional(),
});

export type BookFrontmatter = z.infer<typeof bookSchema>;
