name = "unireadinglist"
compatibility_date = "2024-01-01"

[env.production]
name = "unireadinglist"

[env.preview]
name = "unireadinglist-preview"

# Pages configuration
pages_build_output_dir = "dist"